apiVersion: v1
kind: Service
metadata:
  name: speech-service
  labels:
    app: speech-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: speech-ci-test
  sessionAffinity: None

